# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/data-analytics-olist',
                'doc_host': 'https://dvths.github.io',
                'git_url': 'https://github.com/dvths/data-analytics-olist',
                'lib_path': 'data_analytics_olist'},
  'syms': { 'data_analytics_olist.core': {'data_analytics_olist.core.foo': ('upload_data.html#foo', 'data_analytics_olist/core.py')},
            'data_analytics_olist.upload_data': { 'data_analytics_olist.upload_data.foo': ( 'upload_data.html#foo',
                                                                                            'data_analytics_olist/upload_data.py')}}}