# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_main.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../nbs/00_main.ipynb 3
import os
from sqlalchemy import create_engine 
from .olist_data_extractor import OlistDataExtractor
from .olist_data_loader import OlistDataLoader

# %% ../nbs/00_main.ipynb 4
def main():
    
    BASE_DIR = os.path.dirname(os.getcwd())
    DATA_DIR = os.path.join(BASE_DIR, "data")
    DATA_RAW = os.path.join(DATA_DIR, "raw")
    ZIP_FILE = "olist_data.zip"
    CONNECTION_STRING = "postgresql://root:root@localhost/tutorial_olist"
    DB = create_engine(CONNECTION_STRING)
    
    
    olist_extractor = OlistDataExtractor(
        zip_file=ZIP_FILE, data_dir=DATA_DIR, output_path=DATA_RAW
    )
    
    olist_extractor.exract_data()
    
    olist_loader = OlistDataLoader(datasets_path=DATA_RAW, database_engine=DB)
    
    olist_loader.load_data()
        

# %% ../nbs/00_main.ipynb 5
if __name__ == "__main__":
    main()
