# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_olist_data_extractor.ipynb.

# %% auto 0
__all__ = ['OlistDataExtractor']

# %% ../nbs/01_olist_data_extractor.ipynb 3
import os
from zipfile import ZipFile

# %% ../nbs/01_olist_data_extractor.ipynb 4
class OlistDataExtractor:
    """Extrai os arquivos de dados compactados para o diretório de arquivos brutos """
    
    def __init__(self, zip_file, data_dir, output_path):
        self.data_dir = data_dir
        self.zip_file = zip_file
        self.output_path = output_path

    
    def exract_data(self):
        with ZipFile(os.path.join(self.data_dir, self.zip_file), "r") as data_raw:
            data_raw.extractall(path=os.path.join(self.data_dir, self.output_path))
