ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "data-analytics-olist"
  site-url: "https://dvths.github.io/data-analytics-olist"
  description: "Este estudo para fins didáticos cria uma visão de cliente CRM com o objetivo de analisar os diferentes perfis de clientes da plataforma marketplace Olist."
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/dvths/data-analytics-olist"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/dvths/data-analytics-olist"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
